
name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          bundle install
          npm install

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: src.
          destination: _site
